version: "3.1"

services:
  app:
    build: ./
    ports:
      - 3000:3000
    environment:
      DB_DNS: db
      DB_USER: localuser
      DB_PWD: localpass
    depends_on:
      - "db"
      - "adminer"
    networks:
      - backend

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: localuser
      POSTGRES_PASSWORD: localpass
      POSTGRES_DB: stocks
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$$MYSQL_ROOT_PASSWORD",
        ]
      timeout: 20s
      retries: 10
    networks:
      - backend

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - backend
    depends_on:
      - "db"

networks:
  backend:
