version: '3.1'

services:
  app: 
    build: ./
    ports:
      - 9000:9000
    restart: always
    environment:
      MYSQL_ENDPOINT: db
      MYSQL_USER: localuser
      MYSQL_PWD: localpass
    depends_on:
      - "db"
      - "adminer"
    networks:
      - backend

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: localuser
      MYSQL_PASSWORD: localpass
      MYSQL_DATABASE: books
      MYSQL_ROOT_PASSWORD: passwd
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      timeout: 20s
      retries: 10
    networks:
      - backend

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - backend
    depends_on:
      - "db"
      
networks:
  backend:

